FROM mambaorg/micromamba:1.5.10

WORKDIR /home

COPY --chown=$MAMBA_USER:$MAMBA_USER environment.yml /tmp/environment.yml
RUN micromamba install -y -n base -f /tmp/environment.yml && \
    micromamba clean -a -y

COPY --chown=$MAMBA_USER:$MAMBA_USER . /home

# Run inside the base conda env so python is available
ENTRYPOINT ["micromamba", "run", "-n", "base", "python", "-m", "harmony_service_example"]


