name: Publish Image to DockerHub

on:
  push:
    branches:
      - main
  release:
    types:
      - published

env:
  IMAGE_NAME: seadas/find-make-matchup-harmony

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=long
            type=semver,pattern={{version}}
      - uses: docker/build-push-action@v5
        with:
          context: prototype/matchup-service
          file: prototype/matchup-service/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
